const express = require("express");
const cors = require("cors");
const dotenv = require("dotenv");
dotenv.config();
const connectDB = require("./config/db");
const authRoutes = require("./routes/authRoutes");
const productRoutes = require("./routes/productRoutes");
const orderRoutes = require("./routes/orderRoutes");
const reviewRoutes = require("./routes/reviewRoutes");
const governmentRateRoutes = require("./routes/governmentRateRoutes");
const resourceRoutes = require("./routes/resourceRoutes");
const shopRoutes = require("./routes/shopRoutes");
const dashboardRoutes = require("./routes/dashboardRoutes");
const Farm = require("./models/Farm");
const Crop = require("./models/Crop");
const Inventory = require("./models/Inventory");
const Expense = require("./models/Expense");
const Income = require("./models/Income");
const Harvest = require("./models/Harvest");
const Fertilizer = require("./models/Fertilizer");
const Irrigation = require("./models/Irrigation");
const { protect, authorize } = require("./middleware/authMiddleware");

async function start() {
  await connectDB();
  const app = express();
  const allowed = (process.env.CLIENT_URL || "http://localhost:5173").split(",").map(x => x.trim());
  app.use(cors({ origin: allowed, credentials: true }));
  app.use(express.json({ limit: "2mb" }));
  app.use(express.urlencoded({ extended: true }));
  app.get("/", (req,res) => res.json({ success:true, message:"AgriMind Backend API is running 🌱", version:"2.0.0" }));
  app.get("/api/health", (req,res) => res.json({ success:true, message:"API is healthy", database:"connected" }));
  app.use("/api/auth", authRoutes);
  const resources = [["/api/farms",Farm],["/api/crops",Crop],["/api/inventory",Inventory],["/api/expenses",Expense],["/api/income",Income],["/api/harvests",Harvest],["/api/fertilizers",Fertilizer],["/api/irrigation",Irrigation]];
  for (const [path, Model] of resources) app.use(path, protect, authorize("farmer"), resourceRoutes(Model,{role:"farmer",ownerField:"owner"}));
  app.use("/api/products", productRoutes);
  app.use("/api/orders", orderRoutes);
  app.use("/api/reviews", reviewRoutes);
  app.use("/api/government-rates", governmentRateRoutes);
  app.use("/api/shop", shopRoutes);
  app.use("/api/dashboard", dashboardRoutes);
  app.use((req,res)=>res.status(404).json({success:false,message:"API route not found."}));
  app.use((err,req,res,next)=>{ console.error(err); res.status(500).json({success:false,message:"Internal server error."}); });
  const PORT = process.env.PORT || 5000;
  app.listen(PORT,()=>console.log(`🌱 AgriMind Backend running on http://localhost:${PORT}`));
}
start().catch(err=>{ console.error("Unable to start AgriMind backend:",err.message); process.exit(1); });
